import { NgModule } from '@angular/core';

import {
  ArrayFill,
  ArrayFilter,
  ArrayFrom,
  ArrayIncludes,
  ArrayPluck,
  ArrayPop,
  ArrayShuffle,
  ArraySort,
  ArraySortAsc,
  ArraySortDesc,
  CapitalCase,
  CoerciveBoolean,
  ControlErrors,
  ControlValue,
  Format,
  Initial,
  IsDate,
  IsDateAfter,
  IsDateBefore,
  IsDateBetween,
  IsDateFuture,
  IsDatePast,
  Log,
  ObjectEntries,
  ObjectKeys,
  ObjectValues,
} from './pipes';


@NgModule({
  exports: [
    ArrayFill,
    ArrayFilter,
    ArrayFrom,
    ArrayIncludes,
    ArrayPluck,
    ArrayPop,
    ArrayShuffle,
    ArraySort,
    ArraySortAsc,
    ArraySortDesc,
    CapitalCase,
    CoerciveBoolean,
    ControlErrors,
    ControlValue,
    Format,
    Initial,
    IsDate,
    IsDateAfter,
    IsDateBefore,
    IsDateBetween,
    IsDateFuture,
    IsDatePast,
    Log,
    ObjectEntries,
    ObjectKeys,
    ObjectValues,
  ],
  imports: [
    ArrayFill,
    ArrayFilter,
    ArrayFrom,
    ArrayIncludes,
    ArrayPluck,
    ArrayPop,
    ArrayShuffle,
    ArraySort,
    ArraySortAsc,
    ArraySortDesc,
    CapitalCase,
    CoerciveBoolean,
    ControlErrors,
    ControlValue,
    Format,
    Initial,
    IsDate,
    IsDateAfter,
    IsDateBefore,
    IsDateBetween,
    IsDateFuture,
    IsDatePast,
    Log,
    ObjectEntries,
    ObjectKeys,
    ObjectValues,
  ],
})
export class UtilityPipesModule { }
